# fonctionne test 15 10 19
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: labtest.specialk8s.shop
spec:
  secretName: labtest.specialk8s.shop-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: labtest.specialk8s.shop
  dnsNames:
  - labtest.specialk8s.shop

# old version
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: test.specialk8s.shop
#   namespace: default
# spec:
#   secretName: test.specialk8s.shop-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: test.specialk8s.shop
#   acme:
#     config:
#     - http01: {}
#       domains:
#       - test.specialk8s.shop