# source : https://docs.cert-manager.io/en/latest/tutorials/acme/http-validation.html 
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: labtest.specialk8s.shop
  # namespace: default
spec:
  secretName: labtest.specialk8s.shop-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: labtest.specialk8s.shop
  dnsNames:
  - labtest.specialk8s.shop
