apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: squasta@microsoft.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx



# old version
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     # You must replace this email address with your own.
#     # Let's Encrypt will use this to contact you about expiring
#     # certificates, and issues related to your account.
#     email: squasta@microsoft.com
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       # Secret resource used to store the account's private key.
#       name: prod-issuer-account-key
#     # Add a single challenge solver, HTTP01 using nginx
#     solvers:
#     - http01:
#         ingress:
#           class: nginx